### ISSUE TITLE
Seems to work sporadically

### ISSUE THREAD

**Issue by jerkstorecaller** [emctague/qmlunfuck#1]
Thanks for your README, I was going crazy trying to understand why Qt Creator was complaining that my "import MyQmlTypes 1.0" referred to a non-existent module even though I did everything right. 

However, without using your script, the issue can eventually be resolved, the bug doesn't seem permanent. The project I was working on that drove me to google this issue, after switching and rebuilding, now is detected properly in Qt Creator. I'm back to exactly the same definitions as before, just removed/edited the same 3 lines in the .pro file enough times. There's definitely a Qt Creator bug, but "eventually" it works.

**Comment by emctague** [comment]
I was unable to make it behave no matter what I did through dozens of tries, unfortunately - glad you got it to work on its own.
